# typed: strict
# frozen_string_literal: true

require "fileutils"

module RubyIndexer
  # Persists index entries to disk so that subsequent server starts can load them instead of re-parsing files.
  #
  # Gems are cached one file per gem (keyed by `name-version`), since a gem's files only change when its version
  # changes. The project's own files are cached in a single project snapshot keyed per file by a fingerprint (mtime and
  # size), so that on a warm start only the files that actually changed are re-parsed.
  #
  # Entries are serialized with `Marshal`, which round-trips the entire entry graph (preserving shared `owner`
  # references) in a single dump. The cache is always local and is invalidated whenever the schema version or the Ruby
  # version changes, since `Marshal`'s format is tied to the Ruby version that produced it.
  class IndexCache
    # Bump this whenever the structure of any serialized entry changes, so that stale caches produced by an older
    # version of the Ruby LSP are discarded instead of loaded
    SCHEMA_VERSION = 1 #: Integer

    EXTENSION = ".dump" #: String

    # Reserved cache key for the project snapshot (the index entries of the project's own files). Unlike gems, project
    # files change individually, so the snapshot stores per-file entries plus a fingerprint (mtime and size) used to
    # detect which files changed since the last run
    PROJECT_SNAPSHOT_KEY = "__project__" #: String

    #: (String cache_dir) -> void
    def initialize(cache_dir)
      @cache_dir = cache_dir
      @available = true #: bool
    end

    # Returns the entries cached for the given key or `nil` if there's no valid cache. A cache is considered invalid (a
    # miss) if the file doesn't exist, was produced by a different schema or Ruby version, or is corrupted
    #: (String cache_key) -> Array[Entry]?
    def read(cache_key)
      return unless @available

      path = file_path(cache_key)
      return unless File.exist?(path)

      payload = Marshal.load(File.binread(path)) #: untyped

      unless payload.is_a?(Hash) &&
          payload[:schema_version] == SCHEMA_VERSION &&
          payload[:ruby_version] == RUBY_VERSION
        return
      end

      payload[:entries]
    rescue StandardError => e
      # If the file is corrupted or cannot be deserialized (for example because it was generated by a different Ruby
      # version), we treat it as a cache miss and delete it so that it gets regenerated
      warn("Ruby LSP failed to read index cache #{cache_key}: #{e.message}")
      delete(cache_key)
      nil
    end

    # Persists the given entries under the given cache key. Write failures (such as a read-only file system or a full
    # disk) are swallowed so that they never interrupt indexing
    #: (String cache_key, Array[Entry] entries) -> void
    def write(cache_key, entries)
      return unless ensure_cache_dir

      payload = { schema_version: SCHEMA_VERSION, ruby_version: RUBY_VERSION, entries: entries }
      path = file_path(cache_key)
      tmp_path = "#{path}.#{Process.pid}.tmp"

      # Write to a temporary file and rename it into place so that a concurrent reader never observes a half-written
      # cache file
      File.binwrite(tmp_path, Marshal.dump(payload))
      File.rename(tmp_path, path)
    rescue StandardError => e
      warn("Ruby LSP failed to write index cache #{cache_key}: #{e.message}")
      @available = false
    end

    # Reads the project snapshot, returning a hash of `{ file_path => { stat: [mtime, size], entries: [...] } }`, or
    # `nil` if there's no valid snapshot (missing, different schema or Ruby version, or corrupted)
    #: -> Hash[String, untyped]?
    def read_project_snapshot
      return unless @available

      path = file_path(PROJECT_SNAPSHOT_KEY)
      return unless File.exist?(path)

      payload = Marshal.load(File.binread(path)) #: untyped

      unless payload.is_a?(Hash) &&
          payload[:schema_version] == SCHEMA_VERSION &&
          payload[:ruby_version] == RUBY_VERSION
        return
      end

      payload[:files]
    rescue StandardError => e
      warn("Ruby LSP failed to read project index snapshot: #{e.message}")
      delete(PROJECT_SNAPSHOT_KEY)
      nil
    end

    # Persists the project snapshot. `files` maps each file path to its fingerprint and entries. Write failures are
    # swallowed so that they never interrupt indexing
    #: (Hash[String, untyped] files) -> void
    def write_project_snapshot(files)
      return unless ensure_cache_dir

      payload = { schema_version: SCHEMA_VERSION, ruby_version: RUBY_VERSION, files: files }
      path = file_path(PROJECT_SNAPSHOT_KEY)
      tmp_path = "#{path}.#{Process.pid}.tmp"

      File.binwrite(tmp_path, Marshal.dump(payload))
      File.rename(tmp_path, path)
    rescue StandardError => e
      warn("Ruby LSP failed to write project index snapshot: #{e.message}")
      @available = false
    end

    # Deletes any cache files that aren't part of the current set of valid keys, preventing the cache directory from
    # growing unbounded as gems are upgraded
    #: (Array[String] valid_keys) -> void
    def prune!(valid_keys)
      return unless @available && File.directory?(@cache_dir)

      Dir.glob(File.join(@cache_dir, "*#{EXTENSION}")).each do |path|
        key = File.basename(path, EXTENSION)
        # The project snapshot is managed separately and must never be pruned here
        next if key == PROJECT_SNAPSHOT_KEY

        File.delete(path) unless valid_keys.include?(key)
      end
    rescue StandardError => e
      warn("Ruby LSP failed to prune index cache: #{e.message}")
    end

    private

    #: (String cache_key) -> String
    def file_path(cache_key)
      File.join(@cache_dir, "#{cache_key}#{EXTENSION}")
    end

    #: (String cache_key) -> void
    def delete(cache_key)
      path = file_path(cache_key)
      File.delete(path) if File.exist?(path)
    rescue StandardError
      # Ignore failures to delete a corrupted cache file. It will simply be overwritten the next time we index the gem
    end

    # Ensures the cache directory exists, returning `false` and disabling the cache if it can't be created
    #: -> bool
    def ensure_cache_dir
      return false unless @available
      return true if File.directory?(@cache_dir)

      FileUtils.mkdir_p(@cache_dir)
      true
    rescue StandardError => e
      warn("Ruby LSP failed to create index cache directory: #{e.message}")
      @available = false
      false
    end
  end
end
